name-template: "cocot46plus BMP v$RESOLVED_VERSION ğŸŒˆ"
tag-template: "cocot46plus-bmp-v$RESOLVED_VERSION"
categories:
  - title: "ğŸš€ Features"
    labels:
      - "enhancement"
  - title: "ğŸ›  Improvements"
    label: "improvement"
  - title: "ğŸ› Bug Fixes"
    label: "bug"
  - title: "ğŸ§° Maintenance"
    labels:
      - "chore"
      - "refactoring"
  - title: "â›“ï¸ Dependency update"
    label: "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "enhancement"
      - "improvement"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes
  $CHANGES

  ## How to install
